{% set name = "kagglehub" %}
{% set version = "0.3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kagglehub-{{ version }}.tar.gz
  sha256: d3c8b6250627d665096cd91a9487559bf5ed61be607eaf63d14511b20eea646e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - tqdm
    - packaging

test:
  imports:
    - kagglehub
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kaggle/kagglehub
  summary: Access Kaggle resources anywhere
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
