{% set name = "kagglehub" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kagglehub-{{ version }}.tar.gz
  sha256: 45e75854630a30605b794eb786b3757beccbbea1acca71600642f67b60e0d7bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - tqdm
    - packaging
    - pyyaml

test:
  imports:
    - kagglehub
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kaggle/kagglehub
  summary: Access Kaggle resources anywhere
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
