{% set name = "kagglehub" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kagglehub-{{ version }}.tar.gz
  sha256: 6ebd7765bdbd5d7e69ddd246319e6dea0078bba8ad255f34f44ba6fe5353a056

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - requests
    - tqdm
    - packaging

test:
  imports:
    - kagglehub
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kaggle/kagglehub
  summary: Access Kaggle resources anywhere
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
